NumPy ufuncs
================


What are ufuncs?
-----------------
Ufuncs, or "universal functions", are a core feature of NumPy that allow for element-wise operations on arrays. They are implemented in C for performance and can handle broadcasting, type casting, and several other features.

Why use ufuncs?
----------------
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.

What is vectorization?
-----------------
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [ ]:
# Example
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


Create your own ufunc
-----------------
You can create your own ufunc using the numpy.frompyfunc() function. Here's an example:

```python
import numpy as np

def my_add(x, y):
    return x + y

my_ufunc = np.frompyfunc(my_add, 2, 1)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = my_ufunc(x, y)

print(z)

In [3]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


Simple Arithmetic ufuncs
-----------------
NumPy provides several built-in ufuncs for basic arithmetic operations:

In [4]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


We can use all the arithmetic operators like +, -, *, /, //, %, ** directly on NumPy arrays element-wise.

Rounding Decimals
-----------------


In [6]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

arr = np.around(3.1666, 2)

print(arr)

arr = np.floor([-3.1666, 3.6667])

print(arr)

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


Summation and Product
-----------------


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)


print(newarr)

12
[6 6]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

24
40320


Finding LCM (lowest common multiple) and GCD (greatest common divisor)
-----------------------------------------------------------------------


In [16]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

12
18


In [23]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

3
4


Set Operations
----------------
We can perform set operations like union, intersection, difference, and symmetric difference using NumPy ufuncs.

In [24]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


What is a correct syntax to check the number of dimensions in an array?
----------------
arr.ndim()    Your answer  

arr.ndim    Correct answer  

arr.dim()

arr.dim

What is a correct syntax to return the shape of an array?
----------------
arr.shape()    Your answer

arr.shape    Correct answer

arr.dim()

arr.dimensions