Use numpy for matrix operations. Here is an example of how to perform basic matrix operations using numpy in Python:


In [2]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot_product = np.dot(v1, v2)
print("Dot product:", dot_product)

Dot product: 32


In [7]:
vx = input("Enter x components separated by spaces: ")
vy = input("Enter y components separated by spaces: ")
angle = float(input("Enter angle in degrees: "))
rotation_matrix = np.array([[np.cos(np.radians(angle)), -np.sin(np.radians(angle))],[np.sin(np.radians(angle)), np.cos(np.radians(angle))]])
vec = np.array([float(x) for x in vx.split()] + [float(y) for y in vy.split()])
print("Vector array:\n", vec)
rotated_vec = rotation_matrix.dot(vec.reshape(2, -1))
print("Rotated vector array:\n", rotated_vec)

Vector array:
 [0.5 0.1]
Rotated vector array:
 [[-0.1]
 [ 0.5]]


In [11]:
mat = np.array([[3.5,6,7],
                [6,4.5,8],
                [7,8,5.5]])
r1 = mat[:,1]
r2 = mat[-1,:]
print(r1)
print(r2)

[6.  4.5 8. ]
[7.  8.  5.5]


In [12]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
C = np.dot(A,B)
print("Matrix C:\n", C)

Matrix C:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [13]:
from scipy.spatial.transform import Rotation as R

v = np.array([1,2,3])
r = R.from_euler('z', 20, degrees=True)
v_rotated = r.apply(v)
print("Original vector:", v)
print("Rotated vector:", v_rotated)

Original vector: [1 2 3]
Rotated vector: [0.25565233 2.22140538 3.        ]


In [27]:
for i in range(1,10):
    for j in range(1,i+1):
        print(f"{j}*{i}={i*j}", end="\t")
    print()

1*1=1	
1*2=2	2*2=4	
1*3=3	2*3=6	3*3=9	
1*4=4	2*4=8	3*4=12	4*4=16	
1*5=5	2*5=10	3*5=15	4*5=20	5*5=25	
1*6=6	2*6=12	3*6=18	4*6=24	5*6=30	6*6=36	
1*7=7	2*7=14	3*7=21	4*7=28	5*7=35	6*7=42	7*7=49	
1*8=8	2*8=16	3*8=24	4*8=32	5*8=40	6*8=48	7*8=56	8*8=64	
1*9=9	2*9=18	3*9=27	4*9=36	5*9=45	6*9=54	7*9=63	8*9=72	9*9=81	


In [28]:
R = np.array([[np.sqrt(2)/2, -np.sqrt(2)/2,0],
              [np.sqrt(2)/2, np.sqrt(2)/2,0],
              [0,0,1]])

eigvals, eigvecs = np.linalg.eig(R)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues:
 [0.70710678+0.70710678j 0.70710678-0.70710678j 1.        +0.j        ]
Eigenvectors:
 [[ 0.        -0.70710678j  0.        +0.70710678j  0.        +0.j        ]
 [-0.70710678+0.j         -0.70710678-0.j          0.        +0.j        ]
 [ 0.        -0.j          0.        +0.j          1.        +0.j        ]]
